// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRFJgtdTyQzLd3McuJ64W9z9l0Bxzk8ps',
    appId: '1:916287429194:web:ea2a0d74047ffd3505e4b3',
    messagingSenderId: '916287429194',
    projectId: 'uy19421sbw0axl2htpfhuglpl7z0u1',
    authDomain: 'uy19421sbw0axl2htpfhuglpl7z0u1.firebaseapp.com',
    storageBucket: 'uy19421sbw0axl2htpfhuglpl7z0u1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqr_b8H01J1NbewYHMz-7CmSjX0RMCBVQ',
    appId: '1:916287429194:android:6f5fc56dc27a835205e4b3',
    messagingSenderId: '916287429194',
    projectId: 'uy19421sbw0axl2htpfhuglpl7z0u1',
    storageBucket: 'uy19421sbw0axl2htpfhuglpl7z0u1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYL28s3jkkosTcl84v4IN4OSxecW8uy9w',
    appId: '1:206154666856:ios:d2ea87b855413cf29dbcdd',
    messagingSenderId: '206154666856',
    projectId: 'officialb2b',
    storageBucket: 'officialb2b.firebasestorage.app',
    iosBundleId: 'com.example.b2bmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYL28s3jkkosTcl84v4IN4OSxecW8uy9w',
    appId: '1:206154666856:ios:d2ea87b855413cf29dbcdd',
    messagingSenderId: '206154666856',
    projectId: 'officialb2b',
    storageBucket: 'officialb2b.firebasestorage.app',
    iosBundleId: 'com.example.b2bmobile',
  );
}
